server:
  port: 9095
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 30
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 30
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://myadmin:20170215Zyy@${eureka.instance.hostname}:8761/eureka/
      # defaultZone: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@${eureka.host:172.18.81.2}:${eureka.port:8761}/eureka/
      # defaultZone: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: serve_default
          uri: http://localhost:9005/index.html
          predicates:
            - Path=/
        - id: serve_cauth
          uri: lb://cauth-server
          #uri: http://localhost:9999
          predicates:
            - Path=/cauth/**
          filters:
            - StripPrefix=1
        #- id: serve_kafka
        #  uri: lb://kafka-server
          #uri: http://localhost:8080
        #  predicates:
        #    - Path=/kafka/**
        #  filters:
        #    - StripPrefix=1
        #- id: serve_webcommon
        #  uri: lb://webcommon-server   #该server的名字webcommon-server不能与路径webcommon相同，否则gateway将出现问题
          #uri: http://localhost:7070
        #  predicates:
        #    - Path=/webcommon/**
        #  filters:
        #    - StripPrefix=1
          #- name: Hystrix # Hystrix Filter的名称
          #  args: # Hystrix配置参数
          #    name: fallbackcmd #HystrixCommand的名字
          #    fallbackUri: forward:/fallback #fallback对应的uri

#Hystrix的fallbackcmd的时间
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    com.myworld.cgateway: ERROR
  pattern.file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  path: /home/logs/myworld-cgate.log
  file:
    max-history: 20
    max-size: 10MB

my:
  test:
    security:
      config: This is the Test for config update, 1111
      code:
        sms:
          length: 10
          expireIn: 600
